config/routes.rb
AssembleaSoci::Application.routes.draw do
  resources :delegati
  match 'live' => 'live#index'
  match 'welcome' => 'live#welcome'
  match 'sezioni/elenco' => 'sezioni#elenco', :as => :elencosezioni
  resources :sezioni

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  match 'presenze/report' => 'presenze#report', :as => :report
  match 'presenze/inviadelegati' => 'presenze#invia_delegati', :as => :inviadelegati
  match 'presenze/setdelegato/:socio_id/:presenza_id' => 'presenze#setdelegato', :as => :delega
  match 'presenze/registra/:socio_id(/:condelega)' => 'presenze#registra', :as => :registra

  resources :presenze

  resources :assemblee

  resources :soci

  match '/setassemblea/:assemblea_id' => 'assemblee#setassemblea', :via => :get

  root :to => "assemblee#index"
end

app/controllers/soci_controller.rb
class SociController < ApplicationController

  def index
    @soci = Socio.page(params[:page]).search(params[:search])
  end

  def show
    @socio = Socio.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @socio }
    end
  end

  def new
    @socio = Socio.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @socio }
    end
  end

  # GET /soci/1/edit
  def edit
    @socio = Socio.find(params[:id])
  end

  def create
    @socio = Socio.new(params[:socio])

    respond_to do |format|
      if @socio.save
        format.html { redirect_to @socio, notice: 'Socio was successfully created.' }
        format.json { render json: @socio, status: :created, location: @socio }
      else
        format.html { render action: "new" }
        format.json { render json: @socio.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    @socio = Socio.find(params[:id])

    respond_to do |format|
      if @socio.update_attributes(params[:socio])
        format.html { redirect_to @socio, notice: 'Socio was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @socio.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @socio = Socio.find(params[:id])
    @socio.destroy

    respond_to do |format|
      format.html { redirect_to soci_url }
      format.json { head :no_content }
    end
  end

end

app/helpers/soci_helper.rb
module SociHelper
end

app/views/soci/_elenco.html.erb
<%= will_paginate soci, :renderer => BootstrapPagination::Rails  %>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:socio) %></th>
      <th><%= model_class.human_attribute_name(:codsocio) %></th>
      <th><%= model_class.human_attribute_name(:codtessera) %></th>
      <th><%= model_class.human_attribute_name(:datanascita) %></th>
      <th><%= model_class.human_attribute_name(:sezione) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% soci.each do |socio| %>
      <tr>
        <td><%= link_to socio.socio, socio_path(socio) %></td>
        <td><%= socio.codsocio %></td>
        <td><%= socio.codtessera %></td>
        <td><%= socio.datanascita %></td>
        <td><%= socio.sezione %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_socio_path(socio), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      socio_path(socio),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_socio_path,
            :class => 'btn btn-primary' %>

app/views/soci/_form.html.erb
<%= form_for @socio, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :socio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :socio, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :codsocio, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :codsocio, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :codtessera, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :codtessera, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :datanascita, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :datanascita, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sezione, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sezione, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                soci_path, :class => 'btn' %>
  </div>
<% end %>

app/views/soci/edit.html.erb
<%- model_class = Socio -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/soci/index.html.erb
<%- model_class = Socio -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>

<%= form_tag soci_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search %>
    <%= submit_tag "Cerca", :name => nil %>
  </p>
<% end %>
<%= render 'elenco', :soci => @soci, :model_class => model_class unless @soci.nil? %>

app/views/soci/new.html.erb
<%- model_class = Socio -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/soci/show.html.erb
<%- model_class = Socio -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:socio) %>:</strong></dt>
  <dd><%= @socio.socio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:codsocio) %>:</strong></dt>
  <dd><%= @socio.codsocio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:codtessera) %>:</strong></dt>
  <dd><%= @socio.codtessera %></dd>
  <dt><strong><%= model_class.human_attribute_name(:datanascita) %>:</strong></dt>
  <dd><%= @socio.datanascita %></dd>
  <dt><strong><%= model_class.human_attribute_name(:sezione) %>:</strong></dt>
  <dd><%= @socio.sezione %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              soci_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_socio_path(@socio), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              socio_path(@socio),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>