config/routes.rb
AssembleaSoci::Application.routes.draw do
  resources :delegati
  match 'live' => 'live#index'
  match 'welcome' => 'live#welcome'
  match 'sezioni/elenco' => 'sezioni#elenco', :as => :elencosezioni
  resources :sezioni

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  match 'presenze/report' => 'presenze#report', :as => :report
  match 'presenze/inviadelegati' => 'presenze#invia_delegati', :as => :inviadelegati
  match 'presenze/setdelegato/:socio_id/:presenza_id' => 'presenze#setdelegato', :as => :delega
  match 'presenze/registra/:socio_id(/:condelega)' => 'presenze#registra', :as => :registra

  resources :presenze

  resources :assemblee

  resources :soci

  match '/setassemblea/:assemblea_id' => 'assemblee#setassemblea', :via => :get

  root :to => "assemblee#index"
end

app/controllers/assemblee_controller.rb
class AssembleeController < ApplicationController
  # GET /assemblee
  # GET /assemblee.json
  def index
    @assemblee = Assemblea.page(params[:page]).order('data ASC, nome ASC').all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @assemblee }
    end
  end

  # GET /assemblee/1
  # GET /assemblee/1.json
  def show
    @assemblea = Assemblea.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @assemblea }
    end
  end

  # GET /assemblee/new
  # GET /assemblee/new.json
  def new
    @assemblea = Assemblea.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @assemblea }
    end
  end

  # GET /assemblee/1/edit
  def edit
    @assemblea = Assemblea.find(params[:id])
  end

  # POST /assemblee
  # POST /assemblee.json
  def create
    @assemblea = Assemblea.new(params[:assemblea])

    respond_to do |format|
      if @assemblea.save
        format.html { redirect_to @assemblea, notice: 'Assemblea was successfully created.' }
        format.json { render json: @assemblea, status: :created, location: @assemblea }
      else
        format.html { render action: "new" }
        format.json { render json: @assemblea.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /assemblee/1
  # PUT /assemblee/1.json
  def update
    @assemblea = Assemblea.find(params[:id])

    respond_to do |format|
      if @assemblea.update_attributes(params[:assemblea])
        format.html { redirect_to @assemblea, notice: 'Assemblea was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @assemblea.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /assemblee/1
  # DELETE /assemblee/1.json
  def destroy
    @assemblea = Assemblea.find(params[:id])
    @assemblea.destroy

    respond_to do |format|
      format.html { redirect_to assemblee_url }
      format.json { head :no_content }
    end
  end

  def setassemblea
    @oldid = session[:assemblea_id]
    session[:assemblea_id] = params[:assemblea_id]
    @assid = params[:assemblea_id]
    @nomeass = Assemblea.find(params[:assemblea_id]).nome
  end
end

app/helpers/assemblee_helper.rb
module AssembleeHelper
end

app/views/assemblee/_form.html.erb
<%= form_for @assemblea, :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :nome, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :nome, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sezione_id, :class => 'control-label' %>
    <div class="controls">
      <%= collection_select(:assemblea,:sezione_id,Sezione.all,:id,:nome,:class => 'text_field') %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :sede, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :sede, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :generale, "Assemblea Generale", :class => 'checkbox' %>
    <div class="controls">
      <%= f.check_box :generale, :class => 'number_field' %>
    </div>
  </div>  
  <div class="control-group">
    <%= f.label :data, :class => 'control-label' %>
    <div class="controls">
      <%= f.date_select :data, :class => 'date_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :stato, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :stato, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :eliminato, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :eliminato, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :presidente, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :presidente, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :orainizio, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :orainizio, :class => 'time_select' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :orafine, :class => 'control-label' %>
    <div class="controls">
      <%= f.time_select :orafine, :class => 'time_select' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                assemblee_path, :class => 'btn' %>
  </div>
<% end %>

app/views/assemblee/edit.html.erb
<%- model_class = Assemblea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/assemblee/index.html.erb
<%- model_class = Assemblea -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<div class="text-center">
  <%= will_paginate @assemblee, :renderer => BootstrapPagination::Rails  %>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:data) %></th>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:nome) %></th>
      <th><%= model_class.human_attribute_name(:stato) %></th>
      <th><%= model_class.human_attribute_name(:presidente) %></th>
      <th><%= model_class.human_attribute_name(:orainizio) %></th>
      <th><%= model_class.human_attribute_name(:orafine) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @assemblee.each do |assemblea| %>
      <tr <%= 'class=success' if session[:assemblea_id]==assemblea.id.to_s %> <%= 'id=asbl'+assemblea.id.to_s %>>
        <td><%= l(assemblea.data, :format => :long) %></td>
        <td><%= link_to assemblea.id, assemblea_path(assemblea) %></td>
        <td><%= assemblea.nome %></td>
        <td><%= assemblea.stato %></td>
        <td><%= assemblea.presidente %></td>
        <td><%= l(assemblea.orainizio, :format => :timeonly) %></td>
        <td><%= l(assemblea.orafine, :format => :timeonly) %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_assemblea_path(assemblea), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      assemblea_path(assemblea),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-mini btn-danger' %>
          <%= link_to t('select'), 
                        '#', 
                        :data => { id: assemblea.id },
                        :class => 'scegli btn btn-mini btn-warning' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_assemblea_path,
            :class => 'btn btn-primary' %>

app/views/assemblee/new.html.erb
<%- model_class = Assemblea -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>
<%= render :partial => 'form' %>

app/views/assemblee/setassemblea.json.erb
{ "assemblea_id": "<%= @assid %>", 
  "old_id": "<%= @oldid %>",
  "nomeass": "<%= @nomeass %>" }

app/views/assemblee/show.html.erb
<%- model_class = Assemblea -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:nome) %>:</strong></dt>
  <dd><%= @assemblea.nome %></dd>
  <dt><strong><%= model_class.human_attribute_name(:data) %>:</strong></dt>
  <dd><%= @assemblea.data %></dd>
  <dt><strong><%= model_class.human_attribute_name(:stato) %>:</strong></dt>
  <dd><%= @assemblea.stato %></dd>
  <dt><strong><%= model_class.human_attribute_name(:eliminato) %>:</strong></dt>
  <dd><%= @assemblea.eliminato %></dd>
  <dt><strong><%= model_class.human_attribute_name(:presidente) %>:</strong></dt>
  <dd><%= @assemblea.presidente %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orainizio) %>:</strong></dt>
  <dd><%= @assemblea.orainizio %></dd>
  <dt><strong><%= model_class.human_attribute_name(:orafine) %>:</strong></dt>
  <dd><%= @assemblea.orafine %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              assemblee_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_assemblea_path(@assemblea), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              assemblea_path(@assemblea),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>