config/routes.rb
AssembleaSoci::Application.routes.draw do
  resources :delegati
  match 'live' => 'live#index'
  match 'welcome' => 'live#welcome'
  match 'sezioni/elenco' => 'sezioni#elenco', :as => :elencosezioni
  resources :sezioni

  devise_for :users, path_names: {sign_in: "login", sign_out: "logout"}
  match 'presenze/report' => 'presenze#report', :as => :report
  match 'presenze/inviadelegati' => 'presenze#invia_delegati', :as => :inviadelegati
  match 'presenze/setdelegato/:socio_id/:presenza_id' => 'presenze#setdelegato', :as => :delega
  match 'presenze/registra/:socio_id(/:condelega)' => 'presenze#registra', :as => :registra

  resources :presenze

  resources :assemblee

  resources :soci

  match '/setassemblea/:assemblea_id' => 'assemblee#setassemblea', :via => :get

  root :to => "assemblee#index"
end

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
  <%= image_tag('coopbrand.png', :style => "padding: 0px 20px;", :class => "brand") %>
  <%= link_to content_tag(:i, "", :class => "icon-home"), root_path, :class => "brand" %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
      <%= link_to('Assemblee', assemblee_path) %>
    </li>
    <li>
      <%= link_to('Sezioni', elencosezioni_path) %>
    </li>
    <li>
      <%= link_to('Presenze', presenze_path) %>
    </li>
    <li>
      <%= link_to('Soci', soci_path) %>
    </li>
    <li>
      <%= link_to('Delegati', delegati_path) %>
    </li>
    <li>
      <%= link_to('Edit account', edit_user_registration_path) %>
    </li>
    <li>
      <%= link_to(content_tag(:i, "", :class => "icon-off"), destroy_user_session_path, :method=>'delete') %>
    </li>
    <% if session[:assemblea_id] %>
      <li>
          <%= link_to('Assemblea in corso: ' + Assemblea.find(session[:assemblea_id]).nome, '#', :class => 'text-info', :id => 'curasname') %> 
      </li>
    <% end %>
  <% else %>
    <li>
      <%= link_to('Login', new_user_session_path)  %>
    </li>
    <li>
      <%= link_to('Sign up', new_user_registration_path)  %>
    </li>
  <% end %>
</ul>

app/views/layouts/_user_header.html.erb
<ul class="nav nav-pills pull-right">
  <% if user_signed_in? %>
    <li><%= link_to "Logout", destroy_user_session_path, :method => :delete %></li>
  <% else %>
    <li><%= link_to "Login", new_user_session_path %></li>
    <li><%= link_to "Registrazione", new_user_registration_path %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Assemblee dei soci" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' unless controller_name == 'presenze' && action_name == 'index'%>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>

app/views/layouts/application1.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Assemblea dei Soci</title>
  <!--[if lt IE 9]>
    <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
  <![endif]-->
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
</head>
<body>
  <div class="navbar navbar-fixed-top">
  	<div class="navbar-inner">
      <div class="container">
      	<a class="btn btn-navbar" data-toggle="collapse" data-target=".nav-collapse">
      	  <span class="icon-bar"></span>
       	  <span class="icon-bar"></span>
      	  <span class="icon-bar"></span>
      	</a>	
      	<a class="brand" href="#">Some Store</a>
      	<div class="nav-collapse">
      	  <ul class="nav">
      	    <li><%= link_to "Elenco Soci", soci_path %></li>
      	  	<li><%= link_to "Assemblee", assemblee_path %></li>
      	  	<li><%= link_to "Presenze", presenze_path %></li> 
      	  </ul>
      	</div>
      </div>
    </div>
  </div>
  <div class="container-narrow">
    <div class="masthead">
      <%= render 'layouts/user_header' %>
    </div>
  </div>
  <div class="container">  	
   	<div class="row">
   	  <div class="span9"><%= yield %></div>
   	  <div class="span3">
   	  	<h2>Chi siamo</h2>
   	  	<p>Lorem ipsum dolor sit amet,     consectetur adipisicing elit, sed   do   eiusmod tempor incididunt ut   labore et   dolore magna aliqua.   Ut enim ad minim   veniam, quis   nostrud exercitation   ullamco   laboris nisi ut aliquip ex ea     commodo consequat. Duis aute   irure   dolor in reprehenderit in   voluptate   velit esse cillum   dolore eu fugiat   nulla pariatur.   Excepteur sint   occaecat   cupidatat non proident, sunt   in   culpa qui officia deserunt   mollit   anim id est laborum.</p>
   	  </div>
    </div>
  </div>
</body>
</html>

app/views/layouts/application2.html.erb
<!doctype html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Assemblee dei soci" %></title>
    <meta name="description" content="">
    <meta name="author" content="">
    <%= stylesheet_link_tag "application", :media => "all" %>
    <%= javascript_include_tag "application" %>
    <%= csrf_meta_tags %>
    <%= yield(:head) %>
  </head>
  <body>
    <header class="navbar navbar-fixed-top">
      <nav class="navbar-inner">
        <div class="container">
          <%= render 'layouts/navigation' %>
        </div>
      </nav>
    </header>
    <div id="main" role="main">
      <div class="container">
        <div class="content">
           <div class="row">
            <div class="span12">
              <%= render 'layouts/messages' %>
              <%= yield %>
            </div>
          </div>
          <footer>
          </footer>
        </div>
      </div> <!--! end of .container -->
    </div> <!--! end of #main -->
  </body>
</html>